import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Index";
import Footer from "@/components/footer/Index";
import Sidebar from "@/components/sidebar/Index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coporación RIZO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} overflow-y-scroll overflow-x-hidden`}>
        <Sidebar />
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
